use anyhow::Result;
use std::path::Path;

use crate::cli::ReproduceArgs;
use crate::data::experiment::discover_experiments;

pub fn run(args: ReproduceArgs, base_dir: &Path) -> Result<()> {
    let experiments = discover_experiments(base_dir);
    let exp = experiments
        .iter()
        .find(|e| e.name == args.experiment)
        .ok_or_else(|| anyhow::anyhow!("experiment '{}' not found", args.experiment))?;

    let meta_path = exp.dir.join("meta.json");
    let doc: serde_json::Value = if meta_path.exists() {
        let content = std::fs::read_to_string(&meta_path)?;
        serde_json::from_str(&content)?
    } else {
        anyhow::bail!("no meta.json found for '{}'", args.experiment);
    };

    println!("# Reproduction guide for '{}'", args.experiment);
    println!("# Generated by nuviz reproduce\n");

    // Git info
    if let Some(hash) = doc.get("git_hash").and_then(|v| v.as_str()) {
        println!("# --- Git ---");
        println!("git checkout {}", hash);
        if doc
            .get("git_dirty")
            .and_then(|v| v.as_bool())
            .unwrap_or(false)
        {
            println!("# WARNING: working tree was dirty when experiment ran");
        }
        println!();
    }

    // Python version
    if let Some(py) = doc.get("python_version").and_then(|v| v.as_str()) {
        println!("# --- Python {} ---", py);
    }

    // Pip packages
    if let Some(pkgs) = doc.get("pip_packages").and_then(|v| v.as_array()) {
        if !pkgs.is_empty() {
            println!("pip install \\");
            let pkg_strs: Vec<&str> = pkgs.iter().filter_map(|v| v.as_str()).collect();
            for (i, pkg) in pkg_strs.iter().enumerate() {
                if i < pkg_strs.len() - 1 {
                    println!("  \"{}\" \\", pkg);
                } else {
                    println!("  \"{}\"", pkg);
                }
            }
            println!();
        }
    }

    // GPU / CUDA
    if let Some(gpu) = doc.get("gpu_model").and_then(|v| v.as_str()) {
        println!("# --- Hardware ---");
        println!("# GPU: {}", gpu);
    }
    if let Some(cuda) = doc.get("cuda_version").and_then(|v| v.as_str()) {
        println!("# CUDA: {}", cuda);
    }
    if let Some(host) = doc.get("hostname").and_then(|v| v.as_str()) {
        println!("# Host: {}", host);
    }

    // Config
    if let Some(config) = doc.get("config") {
        if !config.is_null() {
            println!("\n# --- Config ---");
            println!("# {}", serde_json::to_string_pretty(config)?);
        }
    }

    // Seed
    if let Some(seed) = doc.get("seed").and_then(|v| v.as_u64()) {
        println!("\n# Seed: {}", seed);
    }

    // Start time
    if let Some(t) = doc.get("start_time").and_then(|v| v.as_str()) {
        println!("# Originally started: {}", t);
    }

    Ok(())
}
